// 55-Introduccion-a-VueJS/src/App.vue
<script setup>
import { ref, computed } from "vue";
import Header from "./components/Header.vue";
import Button from "./components/Button.vue";

const cantidad = ref(10000);
const meses =  ref(6); 
const MIN = 0;
const MAX = 20000;
const STEP = 100;

// const state = reactive({ // no toma valores primitivos
//   cantidad: 0
// })
const formatearDinero = computed(() => {
  const formatter = new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: 'USD',
  });

  return formatter.format(cantidad.value);
});

const handleChangeDecremento = () => {
  const valor = cantidad.value - STEP;

  if (valor < MIN) {
    alert('Cantidad no valida');
    return;
  }

  cantidad.value = valor;
}

const handleChangeIncremento = () => {
  const valor = cantidad.value + STEP;

  if (valor > MAX) {
    alert('Cantidad no valida');
    return;
  }

  cantidad.value = valor;
}

</script>

<template>
  <div class="my-20 max-w-lg mx-auto bg-white shadow p-10">
    <Header />

    <div class="flex justify-between mt-10">
      <Button 
        :operador="'-'"
        @funcion="handleChangeDecremento" 
      />
      <Button 
        :operador="'+'" @funcion="handleChangeIncremento" 
      />
    </div>

    <div class="my-5">
      <input 
        type="range" 
        class="w-full bg-gray-200 accent-lime-500 hover:accent-lime-600" 
        :min="MIN" 
        :max="MAX"
        :step="STEP" 
        v-model.number="cantidad" 
      />

      <p class="text-center my-10 text-5xl font-extrabold text-indigo-600">
        {{ formatearDinero }}
      </p>
      <h2 class="text-2xl font-extrabold text-gray-500 text-center">
        Elige un <span class="text-indigo-600">Plazo</span> a pagar
      </h2>

      <select 
        class="w-full p-2 bg-white border border-gray-300 rounded-lg text-center text-xl font-bold text-gray-500 mt-5"
        :value="meses"
        v-model.number="meses"
      >
        <option value="6">6 Meses</option>
        <option value="12">12 Meses</option>
        <option value="24">24 Meses</option>

      </select>
    </div>
  </div>
</template>

<style scoped></style>

// 54-Introduccion-a-React/src/App.jsx
/* eslint-disable no-unused-vars */
import { useState } from "react";
import Header from "./components/Header";
import Button from "./components/Button";
import { formatearDinero, calcularTotalPagar } from "./helpers";

function App() {
    // Logica js
    const [cantidad, setCantidad] = useState(10000);
    const [meses, setMeses] = useState(6);

    const MIN = 0;
    const MAX = 20000;
    const STEP = 100;

    function handleChange(e) {
        setCantidad(+e.target.value); // convierte en numero
    }

    function handleClickDecremento() {
        const valor = cantidad - STEP;

        if (valor < MIN) {
            alert("Cantidad no valida");
            return;
        }
        setCantidad(valor);
    }

    function handleClickIncremento() {
        const valor = cantidad + STEP;

        if (valor > MAX) {
            alert("Cantidad no valida");
            return;
        }
        setCantidad(valor);
    }

    // reservado para los templates, lo que se va a mostrar en la pantalla
    return (
        <div className="my-20 max-w-lg mx-auto bg-white shadow p-10">
            <Header />

            <div className="flex justify-between my-6">
                <Button operador="-" fn={handleClickDecremento} />
                <Button operador="+" fn={handleClickIncremento} />
            </div>

            <input
                type="range"
                className="w-full  h-6 bg-gray-200 accent-lime-500 hover:accent-lime-600 "
                onChange={handleChange}
                min={MIN}
                max={MAX}
                step={STEP}
                value={cantidad}
            />

            <p className=" text-center my-10 text-5xl font-extrabold text-indigo-600 ">
                {formatearDinero(cantidad)}
            </p>
            <h2 className="text-2xl font-extrabold text-gray-500 text-center">
                Elige un <span className="text-indigo-600">Plazo</span> a pagar
            </h2>

            <select
                className=" mt-5 w-full p-2 bg-white boder border-gray-300 rounded-lg text-center text-xl font-bold text-gray-500"
                value={meses}
                onChange={(e) => setMeses(+e.target.value)}
            >
                <option value="6">6 Meses</option>
                <option value="12">12 Meses</option>
                <option value="24">24 Meses</option>
            </select>

            <div className="my-5 space-y-3 bg-gray-50 p-5">
                <h2 className="text-2xl font-extrabold text-gray-500 text-center">
                    Resumen <span className="text-indigo-600">de pagos</span> 
                </h2>

                <p className=" text-xl text-gray-500 text-center font-bold">{meses} Meses</p>
                <p className=" text-xl text-gray-500 text-center font-bold">Total a pagar</p>
                <p className=" text-xl text-gray-500 text-center font-bold">Mensuales</p>
            </div>
        </div>
    );
}

export default App;
